# This workflow will run lint checks and unit tests with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Create fake keystore
      run: echo -e 'storePassword=fake_pwd\nkeyPassword=fake_pwd\nkeyAlias=fake_key\nstoreFile=fake_file' > keystore.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Android check (lint)
      run: ./gradlew check

    - name: Unit Tests
      run: ./gradlew test

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lint-and-test-results
        path: |
          app/build/reports/*.html
          app/build/reports/tests
